services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      - SERVER_URL=${SERVER_URL}
      - PORT=${PORT:-9000}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - CSRF_ORIGINS=${CSRF_ORIGINS:-*}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - PRIVATE_JWK=${PRIVATE_JWK}
      - PUBLIC_JWK=${PUBLIC_JWK}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
      - IMAGEKIT_FOLDER_NAME=${IMAGEKIT_FOLDER_NAME}
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PORT=${NEXT_PORT:-9001}
    ports:
      - "${NEXT_PORT:-9001}:${NEXT_PORT:-9001}"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
