version: "3"

services:
  # auth-service:
  #   build:
  #     context: .
  #     dockerfile: apps/auth-service/Dockerfile
  #   command: ["bun", "run", "--hot", "src/index.ts"]
  #   env_file:
  #     - ./apps/auth-service/.env.local
  #   environment:
  #     # Fallbacks if env_file is missing
  #     MONGO_URI: mongodb://mongo:27017
  #     MONGO_DB_NAME: auth_dev
  #     NODE_ENV: development
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - .:/usr/src/app
  #     - bun_cache:/root/.bun
  #   restart: unless-stopped

  mongo:
    image: mongo:8.2.3
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  prom-server:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prom-server
    restart: unless-stopped

volumes:
  bun_cache:
  mongo_data:
  grafana_data:
