import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TanStackProvider from "@/contexts/tanstack";
import AuthProvider from "@/contexts/auth";
import ConfigProvider from "@/contexts/config";
import { CartWishlistProvider } from "@/contexts/cart-wishlist";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanStackProvider>
          <AuthProvider>
            <ConfigProvider>
              <CartWishlistProvider>
                <Toaster />
                {children}
              </CartWishlistProvider>
            </ConfigProvider>
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
